/* Generated By:JavaCC: Do not edit this line. master_sintaxConstants.java */
package gramatica.archivo_maestro;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface master_sintaxConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DB = 6;
  /** RegularExpression Id. */
  int C_DB = 7;
  /** RegularExpression Id. */
  int NOMBRE = 8;
  /** RegularExpression Id. */
  int C_NOMBRE = 9;
  /** RegularExpression Id. */
  int PATH = 10;
  /** RegularExpression Id. */
  int C_PATH = 11;
  /** RegularExpression Id. */
  int NUM = 12;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 13;
  /** RegularExpression Id. */
  int IDEN = 14;
  /** RegularExpression Id. */
  int CADENA = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<DB>\"",
    "\"</DB>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "<NUM>",
    "<DECIMAL_LITERAL>",
    "<IDEN>",
    "<CADENA>",
  };

}
