/* SintacticoTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. SintacticoTokenManager.java */
package gramatica;
import ArbolAST.Nodo;
import javax.swing.JOptionPane;

/** Token Manager. */
@SuppressWarnings("unused")public class SintacticoTokenManager implements SintacticoConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xfffffffe00000000L) != 0L || (active1 & 0x33fffffffL) != 0L)
         {
            jjmatchedKind = 98;
            return 17;
         }
         return -1;
      case 1:
         if ((active0 & 0xdff3fdb800000000L) != 0L || (active1 & 0x33ff7ffffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return 17;
         }
         if ((active0 & 0x200c024600000000L) != 0L || (active1 & 0x80000L) != 0L)
            return 17;
         return -1;
      case 2:
         if ((active1 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xdefffffc00000000L) != 0L || (active1 & 0x33ff7efffL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 2;
            return 17;
         }
         if ((active0 & 0x100000000000000L) != 0L)
            return 17;
         return -1;
      case 3:
         if ((active1 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active1 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0xdeffff6800000000L) != 0L || (active1 & 0x30fb3cffdL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 3;
            }
            return 17;
         }
         if ((active0 & 0x9400000000L) != 0L || (active1 & 0x30402002L) != 0L)
            return 17;
         return -1;
      case 4:
         if ((active0 & 0x9effe76800000000L) != 0L || (active1 & 0x22593ce7dL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 4;
            }
            return 17;
         }
         if ((active1 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active1 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x4000180000000000L) != 0L || (active1 & 0x108200180L) != 0L)
            return 17;
         return -1;
      case 5:
         if ((active1 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active1 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x9abf974800000000L) != 0L || (active1 & 0x22193ce7dL) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 5;
            return 17;
         }
         if ((active0 & 0x440602000000000L) != 0L || (active1 & 0x4000000L) != 0L)
            return 17;
         return -1;
      case 6:
         if ((active1 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active1 & 0x1000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 1;
            }
            return -1;
         }
         if ((active0 & 0x1827950800000000L) != 0L || (active1 & 0x220928e60L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 6;
            return 17;
         }
         if ((active0 & 0x8298024000000000L) != 0L || (active1 & 0x101401dL) != 0L)
            return 17;
         return -1;
      case 7:
         if ((active0 & 0x822100800000000L) != 0L || (active1 & 0x200000e60L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 7;
            return 17;
         }
         if ((active1 & 0x40000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x1005850000000000L) != 0L || (active1 & 0x20928000L) != 0L)
            return 17;
         return -1;
      case 8:
         if ((active0 & 0x820100800000000L) != 0L || (active1 & 0xe60L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 8;
            return 17;
         }
         if ((active0 & 0x2000000000000L) != 0L || (active1 & 0x200000000L) != 0L)
            return 17;
         return -1;
      case 9:
         if ((active1 & 0xe20L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 98;
               jjmatchedPos = 9;
            }
            return 17;
         }
         if ((active0 & 0x820100800000000L) != 0L || (active1 & 0x40L) != 0L)
            return 17;
         return -1;
      case 10:
         if ((active1 & 0xe20L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 10;
            return 17;
         }
         if ((active0 & 0x20000000000000L) != 0L)
            return 17;
         return -1;
      case 11:
         if ((active1 & 0xe20L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 11;
            return 17;
         }
         return -1;
      case 12:
         if ((active1 & 0x600L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 12;
            return 17;
         }
         if ((active1 & 0x820L) != 0L)
            return 17;
         return -1;
      case 13:
         if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 13;
            return 17;
         }
         if ((active1 & 0x200L) != 0L)
            return 17;
         return -1;
      case 14:
         if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 14;
            return 17;
         }
         return -1;
      case 15:
         if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 98;
            jjmatchedPos = 15;
            return 17;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 16;
         return jjMoveStringLiteralDfa1_0(0x200L, 0x0L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x8000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 22);
      case 41:
         return jjStopAtPos(0, 23);
      case 42:
         return jjStopAtPos(0, 19);
      case 43:
         return jjStopAtPos(0, 20);
      case 44:
         return jjStopAtPos(0, 27);
      case 45:
         jjmatchedKind = 21;
         return jjMoveStringLiteralDfa1_0(0x20000000L, 0x0L);
      case 46:
         return jjStopAtPos(0, 32);
      case 47:
         return jjStopAtPos(0, 18);
      case 58:
         return jjStopAtPos(0, 31);
      case 59:
         return jjStopAtPos(0, 26);
      case 60:
         jjmatchedKind = 10;
         return jjMoveStringLiteralDfa1_0(0x1000L, 0x100000000000L);
      case 61:
         jjmatchedKind = 28;
         return jjMoveStringLiteralDfa1_0(0x100L, 0x0L);
      case 62:
         jjmatchedKind = 11;
         return jjMoveStringLiteralDfa1_0(0x2000L, 0x200000000000L);
      case 64:
         return jjStopAtPos(0, 30);
      case 94:
         return jjStopAtPos(0, 17);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0xa00000000000000L, 0x40401L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x40400000000000L, 0x400040L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x1201000000000L, 0x814100L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x400c024000000000L, 0x34080000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x2000000000000000L, 0x20000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x180000000000L, 0x100000010L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1000040000000000L, 0x1000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xa00L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x90002000000000L, 0x0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x100008000000000L, 0x108020L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa1_0(0x400000000000000L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x8L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x20000e00000000L, 0x0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000080L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x200006L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x208000000L);
      case 123:
         return jjStopAtPos(0, 24);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x4000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 25);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         break;
      case 45:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L, active1, 0L);
      case 60:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 108);
         break;
      case 61:
         if ((active0 & 0x100L) != 0L)
            return jjStopAtPos(1, 8);
         else if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(1, 13);
         break;
      case 62:
         if ((active1 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 109);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000409000000000L, active1, 0x1388180c0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000000L, active1, 0L);
      case 69:
      case 101:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2e1a4800000000L, active1, 0x202100008L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000000L, active1, 0L);
      case 73:
      case 105:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x10400000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20a01L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L, active1, 0L);
      case 78:
      case 110:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 61, 17);
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000000L, active1, 0x1200000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x4141200000000000L, active1, 0x4405000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000000L, active1, 0x120L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L, active1, 0x40006L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000000L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000000L, active1, 0x2410L);
      case 124:
         if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(1, 14);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0xa02L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x4580000000000L, active1, 0x8040000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000L, active1, 0x100L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000000L, active1, 0x220000L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8020000800000000L, active1, 0x100006000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000000L, active1, 0x10000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x4008200400000000L, active1, 0x10L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000L, active1, 0x400020L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 56, 17);
         return jjMoveStringLiteralDfa3_0(active0, 0x240008000000000L, active1, 0x200900000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x1002001000000000L, active1, 0x8040L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x800020000000000L, active1, 0x31000409L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000004L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2000000L);
      case 124:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 43:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L, active1, 0L);
      case 65:
      case 97:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 17);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800104L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4010000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x200030L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000000L, active1, 0x200000000L);
      case 69:
      case 101:
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 92;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x12a8026800000000L, active1, 0x21000041L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x180000000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x8000000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L, active1, 0L);
      case 76:
      case 108:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 86, 17);
         return jjMoveStringLiteralDfa4_0(active0, 0x4800000000000L, active1, 0x80L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x120000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L, active1, 0x1000L);
      case 79:
      case 111:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 17);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 36, 17);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(3, 77, 17);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000000L, active1, 0x4408L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(3, 65, 17);
         return jjMoveStringLiteralDfa4_0(active0, 0x50040000000000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x100008000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x402200000000000L, active1, 0x2000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000000L, active1, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xa00L);
      case 124:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x40000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 32:
         if ((active1 & 0x2000000L) != 0L)
            return jjStopAtPos(4, 89);
         break;
      case 43:
         if ((active0 & 0x20000000L) != 0L)
            return jjStopAtPos(4, 29);
         break;
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x40L);
      case 65:
      case 97:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 71, 17);
         return jjMoveStringLiteralDfa5_0(active0, 0xc46300000000000L, active1, 0x200000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x20004800000000L, active1, 0x804000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x800000000000L, active1, 0x40000L);
      case 69:
      case 101:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 62, 17);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0xa20L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x218000000000000L, active1, 0x1000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L, active1, 0x130410L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L, active1, 0x4000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x80020000000000L, active1, 0L);
      case 79:
      case 111:
         if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(4, 85, 17);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 91, 17);
         else if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 96, 17);
         break;
      case 82:
      case 114:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 72, 17);
         return jjMoveStringLiteralDfa5_0(active0, 0x9000000000000000L, active1, 0xdL);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x12000000000L, active1, 0x20000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L, active1, 0x1000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000L, active1, 0xa00L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x298000000000000L, active1, 0x14001L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000800000000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x200000060L);
      case 69:
      case 101:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 90, 17);
         return jjMoveStringLiteralDfa6_0(active0, 0x8001020000000000L, active1, 0x1040000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x20000004L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000000L, active1, 0x1000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x20408L);
      case 79:
      case 111:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 37, 17);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8010L);
      case 80:
      case 112:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 46, 17);
         break;
      case 82:
      case 114:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 17);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 54, 17);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 58, 17);
         return jjMoveStringLiteralDfa6_0(active0, 0x4010000000000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000004000000000L, active1, 0x800000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x2800000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1004010000000000L, active1, 0x20040L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x400L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x200800000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x800L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x820040800000000L, active1, 0x20L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000000L, active1, 0x20000000L);
      case 78:
      case 110:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(6, 68, 17);
         break;
      case 79:
      case 111:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 38, 17);
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(6, 66, 17);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(6, 67, 17);
         else if ((active1 & 0x1000L) != 0L)
            return jjStopAtPos(6, 76);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x100000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x200L);
      case 82:
      case 114:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 41, 17);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 51, 17);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 52, 17);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 55, 17);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 57, 17);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(6, 64, 17);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 78, 17);
         else if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(6, 80, 17);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 88, 17);
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000L, active1, 0x8000L);
      case 83:
      case 115:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 63, 17);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x40000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000L, active1, 0L);
      case 67:
      case 99:
         if ((active1 & 0x40000L) != 0L)
            return jjStopAtPos(7, 82);
         break;
      case 68:
      case 100:
         if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 79, 17);
         break;
      case 69:
      case 101:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(7, 93, 17);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x20L);
      case 79:
      case 111:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 48, 17);
         return jjMoveStringLiteralDfa8_0(active0, 0x20100800000000L, active1, 0x800L);
      case 80:
      case 112:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 47, 17);
         break;
      case 82:
      case 114:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 42, 17);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 50, 17);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 60, 17);
         else if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(7, 81, 17);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(7, 87, 17);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x200000600L);
      case 83:
      case 115:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 40, 17);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(7, 84, 17);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x40L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa8_0(active0, 0x800000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000000000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x220L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000800000000L, active1, 0L);
      case 79:
      case 111:
         if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(8, 97, 17);
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x40L);
      case 82:
      case 114:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 49, 17);
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000000L, active1, 0x800L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
         }
         else if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 44, 17);
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000000L, active1, 0x800L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x20L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x600L);
      case 82:
      case 114:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 59, 17);
         break;
      case 83:
      case 115:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(9, 70, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x200L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x400L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x820L);
      case 82:
      case 114:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 53, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, active1);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active1, 0x800L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active1, 0x400L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active1, 0x200L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active1, 0x20L);
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, active1);
}
private int jjMoveStringLiteralDfa12_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(10, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, active1);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(12, 75, 17);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active1, 0x200L);
      case 79:
      case 111:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(12, 69, 17);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa13_0(active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, active1);
}
private int jjMoveStringLiteralDfa13_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(11, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, active1);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(13, 73, 17);
         return jjMoveStringLiteralDfa14_0(active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, active1);
}
private int jjMoveStringLiteralDfa14_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(12, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, active1);
      return 14;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa15_0(active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, active1);
}
private int jjMoveStringLiteralDfa15_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(13, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1);
      return 15;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         return jjMoveStringLiteralDfa16_0(active1, 0x400L);
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1);
}
private int jjMoveStringLiteralDfa16_0(long old1, long active1){
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(14, 0L, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, 0L, active1);
      return 16;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(16, 74, 17);
         break;
      default :
         break;
   }
   return jjStartNfa_0(15, 0L, active1);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 64;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 94)
                        kind = 94;
                     { jjCheckNAddTwoStates(13, 14); }
                  }
                  else if (curChar == 39)
                     { jjCheckNAddStates(0, 7); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(19, 20); }
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 5;
                  if (curChar == 35)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(8, 10); }
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 3:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(6, 7); }
                  break;
               case 6:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(6, 7); }
                  break;
               case 7:
                  if (curChar == 42)
                     { jjCheckNAddStates(11, 14); }
                  break;
               case 8:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(8, 9); }
                  break;
               case 9:
                  if ((0xfffffbf7ffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(6, 7); }
                  break;
               case 10:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 11:
                  if (curChar == 35 && kind > 7)
                     kind = 7;
                  break;
               case 12:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  { jjCheckNAddTwoStates(13, 14); }
                  break;
               case 14:
                  if (curChar != 46)
                     break;
                  if (kind > 94)
                     kind = 94;
                  { jjCheckNAdd(15); }
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  { jjCheckNAdd(15); }
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 18:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(19, 20); }
                  break;
               case 19:
                  if ((0xfffffffbfffff9ffL & l) != 0L)
                     { jjCheckNAddTwoStates(19, 20); }
                  break;
               case 20:
                  if (curChar == 34 && kind > 101)
                     kind = 101;
                  break;
               case 21:
                  if (curChar == 39)
                     { jjCheckNAddStates(0, 7); }
                  break;
               case 23:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(15, 17); }
                  break;
               case 24:
                  if ((0xffffffffffffd9ffL & l) != 0L)
                     { jjCheckNAddStates(15, 17); }
                  break;
               case 25:
                  if (curChar == 39 && kind > 99)
                     kind = 99;
                  break;
               case 26:
                  if (curChar == 48)
                     { jjCheckNAdd(27); }
                  break;
               case 27:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(28); }
                  break;
               case 28:
                  if (curChar == 45)
                     { jjCheckNAddStates(18, 20); }
                  break;
               case 29:
                  if (curChar == 48)
                     { jjCheckNAdd(30); }
                  break;
               case 30:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(31); }
                  break;
               case 31:
                  if (curChar == 45)
                     { jjCheckNAdd(32); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(32, 33); }
                  break;
               case 33:
                  if (curChar == 39 && kind > 102)
                     kind = 102;
                  break;
               case 34:
                  if (curChar == 49)
                     { jjAddStates(21, 23); }
                  break;
               case 35:
                  if (curChar == 48)
                     { jjCheckNAdd(31); }
                  break;
               case 36:
                  if (curChar == 49)
                     { jjCheckNAdd(31); }
                  break;
               case 37:
                  if (curChar == 50)
                     { jjCheckNAdd(31); }
                  break;
               case 38:
                  if ((0xe000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(28); }
                  break;
               case 40:
                  if (curChar == 48)
                     { jjCheckNAdd(41); }
                  break;
               case 41:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(42); }
                  break;
               case 42:
                  if (curChar == 45)
                     { jjCheckNAddStates(24, 26); }
                  break;
               case 43:
                  if (curChar == 48)
                     { jjCheckNAdd(44); }
                  break;
               case 44:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(45); }
                  break;
               case 45:
                  if (curChar == 45)
                     { jjCheckNAdd(46); }
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(46, 47); }
                  break;
               case 47:
                  if (curChar == 32)
                     { jjCheckNAddStates(27, 29); }
                  break;
               case 48:
                  if (curChar == 48)
                     { jjCheckNAdd(49); }
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x7f000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x7f000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if (curChar == 39 && kind > 106)
                     kind = 106;
                  break;
               case 57:
                  if ((0x6000000000000L & l) != 0L)
                     { jjCheckNAdd(49); }
                  break;
               case 58:
                  if (curChar == 49)
                     { jjAddStates(30, 32); }
                  break;
               case 59:
                  if (curChar == 48)
                     { jjCheckNAdd(45); }
                  break;
               case 60:
                  if (curChar == 49)
                     { jjCheckNAdd(45); }
                  break;
               case 61:
                  if (curChar == 50)
                     { jjCheckNAdd(45); }
                  break;
               case 62:
                  if ((0xe000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(42); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 17:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 98)
                     kind = 98;
                  { jjCheckNAdd(17); }
                  break;
               case 1:
                  { jjAddStates(8, 10); }
                  break;
               case 6:
               case 9:
                  { jjCheckNAddTwoStates(6, 7); }
                  break;
               case 19:
                  { jjAddStates(33, 34); }
                  break;
               case 22:
                  if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x14400040144000L & l) != 0L)
                     { jjCheckNAddStates(15, 17); }
                  break;
               case 24:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(15, 17); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(8, 10); }
                  break;
               case 6:
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(6, 7); }
                  break;
               case 19:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(33, 34); }
                  break;
               case 24:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(15, 17); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 64 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   22, 24, 26, 27, 38, 40, 41, 62, 1, 2, 4, 8, 9, 10, 11, 22, 
   24, 25, 29, 30, 34, 35, 36, 37, 43, 44, 58, 48, 49, 57, 59, 60, 
   61, 19, 20, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, "\75\75", "\41\75", "\74", 
"\76", "\74\75", "\76\75", "\174\174", "\46\46", "\41", "\136", "\57", "\52", "\53", 
"\55", "\50", "\51", "\173", "\175", "\73", "\54", "\75", "\55\55\174\53\53", "\100", 
"\72", "\56", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, "\74\74", "\76\76", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public SintacticoTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public SintacticoTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 64; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffff01L, 0x346f7fffffffL, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[64];
    private final int[] jjstateSet = new int[2 * 64];

    
    protected char curChar;
}
