/* Generated By:JavaCC: Do not edit this line. SintacticoConstants.java */
package gramatica;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SintacticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int IIG = 8;
  /** RegularExpression Id. */
  int NOIG = 9;
  /** RegularExpression Id. */
  int MENOR = 10;
  /** RegularExpression Id. */
  int MAYOR = 11;
  /** RegularExpression Id. */
  int MENORI = 12;
  /** RegularExpression Id. */
  int MAYORI = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int AND = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int potencia = 17;
  /** RegularExpression Id. */
  int div = 18;
  /** RegularExpression Id. */
  int mult = 19;
  /** RegularExpression Id. */
  int mas = 20;
  /** RegularExpression Id. */
  int menos = 21;
  /** RegularExpression Id. */
  int apar = 22;
  /** RegularExpression Id. */
  int cpar = 23;
  /** RegularExpression Id. */
  int alla = 24;
  /** RegularExpression Id. */
  int clla = 25;
  /** RegularExpression Id. */
  int ptc = 26;
  /** RegularExpression Id. */
  int coma = 27;
  /** RegularExpression Id. */
  int ASIG = 28;
  /** RegularExpression Id. */
  int key = 29;
  /** RegularExpression Id. */
  int SI = 30;
  /** RegularExpression Id. */
  int SINO = 31;
  /** RegularExpression Id. */
  int SELECCIONA = 32;
  /** RegularExpression Id. */
  int CASO = 33;
  /** RegularExpression Id. */
  int DEFECTO = 34;
  /** RegularExpression Id. */
  int PARA = 35;
  /** RegularExpression Id. */
  int MIENTRAS = 36;
  /** RegularExpression Id. */
  int DETENER = 37;
  /** RegularExpression Id. */
  int IMPRIMIR = 38;
  /** RegularExpression Id. */
  int FECHA = 39;
  /** RegularExpression Id. */
  int FECHA_HORA = 40;
  /** RegularExpression Id. */
  int CONTAR = 41;
  /** RegularExpression Id. */
  int BACKUP = 42;
  /** RegularExpression Id. */
  int USQLDUMP = 43;
  /** RegularExpression Id. */
  int COMPLETO = 44;
  /** RegularExpression Id. */
  int RESTAURAR = 45;
  /** RegularExpression Id. */
  int DECLARAR = 46;
  /** RegularExpression Id. */
  int DENEGAR = 47;
  /** RegularExpression Id. */
  int OTORGAR = 48;
  /** RegularExpression Id. */
  int SELECCIONAR = 49;
  /** RegularExpression Id. */
  int BORRAR = 50;
  /** RegularExpression Id. */
  int ORDENAR = 51;
  /** RegularExpression Id. */
  int POR = 52;
  /** RegularExpression Id. */
  int AGREGAR = 53;
  /** RegularExpression Id. */
  int QUITAR = 54;
  /** RegularExpression Id. */
  int ACTUALIZAR = 55;
  /** RegularExpression Id. */
  int INSERTAR = 56;
  /** RegularExpression Id. */
  int EN = 57;
  /** RegularExpression Id. */
  int DONDE = 58;
  /** RegularExpression Id. */
  int VALORES = 59;
  /** RegularExpression Id. */
  int ALTERAR = 60;
  /** RegularExpression Id. */
  int USAR = 61;
  /** RegularExpression Id. */
  int USUARIO = 62;
  /** RegularExpression Id. */
  int RETORNO = 63;
  /** RegularExpression Id. */
  int FUNCION = 64;
  /** RegularExpression Id. */
  int PROCEDIMIENTO = 65;
  /** RegularExpression Id. */
  int OBJECTO = 66;
  /** RegularExpression Id. */
  int BASE_DATOS = 67;
  /** RegularExpression Id. */
  int TABLA = 68;
  /** RegularExpression Id. */
  int CREAR = 69;
  /** RegularExpression Id. */
  int PK = 70;
  /** RegularExpression Id. */
  int AUTO_INCREMENT = 71;
  /** RegularExpression Id. */
  int FK = 72;
  /** RegularExpression Id. */
  int NOT_NULL = 73;
  /** RegularExpression Id. */
  int NULO = 74;
  /** RegularExpression Id. */
  int BOOL = 75;
  /** RegularExpression Id. */
  int CHAR = 76;
  /** RegularExpression Id. */
  int INTEGER = 77;
  /** RegularExpression Id. */
  int TEXT = 78;
  /** RegularExpression Id. */
  int DOUBLE = 79;
  /** RegularExpression Id. */
  int VACIO = 80;
  /** RegularExpression Id. */
  int DATE = 81;
  /** RegularExpression Id. */
  int DATETIME = 82;
  /** RegularExpression Id. */
  int NUM = 83;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 84;
  /** RegularExpression Id. */
  int FALSE = 85;
  /** RegularExpression Id. */
  int TRUE = 86;
  /** RegularExpression Id. */
  int IDEN = 87;
  /** RegularExpression Id. */
  int CARACTER = 88;
  /** RegularExpression Id. */
  int VAL_CARAC = 89;
  /** RegularExpression Id. */
  int CADENA = 90;
  /** RegularExpression Id. */
  int DATE_EXP = 91;
  /** RegularExpression Id. */
  int DIA = 92;
  /** RegularExpression Id. */
  int MES = 93;
  /** RegularExpression Id. */
  int ANIO = 94;
  /** RegularExpression Id. */
  int DATE_TIME_EXP = 95;
  /** RegularExpression Id. */
  int HOUR = 96;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\"^\"",
    "\"/\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"@\"",
    "\"SI\"",
    "\"SINO\"",
    "\"SELECCIONA\"",
    "\"CASO\"",
    "\"DEFECTO\"",
    "\"PARA\"",
    "\"MIENTRAS\"",
    "\"DETENER\"",
    "\"IMPRIMIR\"",
    "\"FECHA\"",
    "\"FECHA_HORA\"",
    "\"CONTAR\"",
    "\"BACKUP\"",
    "\"USQLDUMP\"",
    "\"COMPLETO\"",
    "\"RESTAURAR\"",
    "\"DECLARAR\"",
    "\"DENEGAR\"",
    "\"OTORGAR\"",
    "\"SELECCIONAR\"",
    "\"BORRAR\"",
    "\"ORDENAR\"",
    "\"POR\"",
    "\"AGREGAR\"",
    "\"QUITAR\"",
    "\"ACTUALIZAR\"",
    "\"INSERTAR\"",
    "\"EN\"",
    "\"DONDE\"",
    "\"VALORES\"",
    "\"ALTERAR\"",
    "\"USAR\"",
    "\"USUARIO\"",
    "\"RETORNO\"",
    "\"FUNCION\"",
    "\"PROCEDIMIENTO\"",
    "\"OBJECTO\"",
    "\"BASE_DATOS\"",
    "\"TABLA\"",
    "\"CREAR\"",
    "\"Llave_Primaria\"",
    "\"Autoincrementable\"",
    "\"Llave_Foranea\"",
    "\"No Nulo\"",
    "\"Nulo\"",
    "\"BOOL\"",
    "\"caracter\"",
    "\"INTEGER\"",
    "\"TEXT \"",
    "\"DOUBLE\"",
    "\"VACIO\"",
    "\"DATE\"",
    "\"DATETIME\"",
    "<NUM>",
    "<DECIMAL_LITERAL>",
    "\"falso\"",
    "\"verdadero\"",
    "<IDEN>",
    "<CARACTER>",
    "<VAL_CARAC>",
    "<CADENA>",
    "<DATE_EXP>",
    "<DIA>",
    "<MES>",
    "<ANIO>",
    "<DATE_TIME_EXP>",
    "<HOUR>",
  };

}
