/* Generated By:JavaCC: Do not edit this line. registro_objConstants.java */
package gramatica.archivo_objeto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface registro_objConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Obj = 6;
  /** RegularExpression Id. */
  int C_Obj = 7;
  /** RegularExpression Id. */
  int Tabla = 8;
  /** RegularExpression Id. */
  int C_Tabla = 9;
  /** RegularExpression Id. */
  int Attr = 10;
  /** RegularExpression Id. */
  int C_Attr = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int BOOL = 13;
  /** RegularExpression Id. */
  int TEXT = 14;
  /** RegularExpression Id. */
  int C_INT = 15;
  /** RegularExpression Id. */
  int C_BOOL = 16;
  /** RegularExpression Id. */
  int C_TEXT = 17;
  /** RegularExpression Id. */
  int NOMBRE = 18;
  /** RegularExpression Id. */
  int C_NOMBRE = 19;
  /** RegularExpression Id. */
  int PATH = 20;
  /** RegularExpression Id. */
  int C_PATH = 21;
  /** RegularExpression Id. */
  int NUM = 22;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 23;
  /** RegularExpression Id. */
  int IDEN = 24;
  /** RegularExpression Id. */
  int CADENA = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<Obj>\"",
    "\"</Obj>\"",
    "\"<Tabla>\"",
    "\"</Tabla>\"",
    "\"<attr>\"",
    "\"</attr>\"",
    "\"<int>\"",
    "\"<bool>\"",
    "\"<text>\"",
    "\"</int>\"",
    "\"</bool>\"",
    "\"</text>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "<NUM>",
    "<DECIMAL_LITERAL>",
    "<IDEN>",
    "<CADENA>",
  };

}
