/* Generated By:JavaCC: Do not edit this line. registro_objConstants.java */
package gramatica.archivo_objeto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface registro_objConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Obj = 6;
  /** RegularExpression Id. */
  int C_Obj = 7;
  /** RegularExpression Id. */
  int Tabla = 8;
  /** RegularExpression Id. */
  int C_Tabla = 9;
  /** RegularExpression Id. */
  int Attr = 10;
  /** RegularExpression Id. */
  int C_Attr = 11;
  /** RegularExpression Id. */
  int DATE = 12;
  /** RegularExpression Id. */
  int DATETIME = 13;
  /** RegularExpression Id. */
  int C_DATE = 14;
  /** RegularExpression Id. */
  int C_DATETIME = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int BOOL = 17;
  /** RegularExpression Id. */
  int TEXT = 18;
  /** RegularExpression Id. */
  int C_INT = 19;
  /** RegularExpression Id. */
  int C_BOOL = 20;
  /** RegularExpression Id. */
  int C_TEXT = 21;
  /** RegularExpression Id. */
  int NOMBRE = 22;
  /** RegularExpression Id. */
  int C_NOMBRE = 23;
  /** RegularExpression Id. */
  int PATH = 24;
  /** RegularExpression Id. */
  int C_PATH = 25;
  /** RegularExpression Id. */
  int NOT_NULL = 26;
  /** RegularExpression Id. */
  int NULO = 27;
  /** RegularExpression Id. */
  int PK = 28;
  /** RegularExpression Id. */
  int AUTO_INCREMENT = 29;
  /** RegularExpression Id. */
  int FK = 30;
  /** RegularExpression Id. */
  int NUM = 31;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 32;
  /** RegularExpression Id. */
  int IDEN = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<Obj>\"",
    "\"</Obj>\"",
    "\"<Tabla>\"",
    "\"</Tabla>\"",
    "\"<attr>\"",
    "\"</attr>\"",
    "\"<DATE>\"",
    "\"<DATETIME>\"",
    "\"</DATE>\"",
    "\"</DATETIME>\"",
    "\"<integer>\"",
    "\"<bool>\"",
    "\"<text>\"",
    "\"</integer>\"",
    "\"</bool>\"",
    "\"</text>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"No Nulo\"",
    "\"Nulo\"",
    "\"Llave_Primaria\"",
    "\"Autoincrementable\"",
    "\"Llave_Foranea\"",
    "<NUM>",
    "<DECIMAL_LITERAL>",
    "<IDEN>",
  };

}
