/* registro_db.java */
/* Generated By:JavaCC: Do not edit this line. registro_db.java */
package gramatica.db;
import ArbolAST.Nodo;
import javax.swing.JOptionPane;


public class registro_db implements registro_dbConstants {
public static Nodo root=null;

 public Nodo retornarArbol(){
        return root;
 }
 public static void main(String args[]) throws ParseException
        {
                try{
                        registro_db miParser = new registro_db(System.in);
                    root = miParser .Inicio();
                    JOptionPane.showMessageDialog(null, "Parseo Correcto", "COMPI2", 1);
                }catch(ParseException e){
                        System.out.println("Error al parsear, "+e.getMessage());
                        JOptionPane.showMessageDialog(null, "Parseo INCORRECTO", "COMPI2", 0);
                }

        }

  final public Nodo Inicio() throws ParseException {Nodo raiz,r;
raiz= new Nodo("registro_db",0,0);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Procedure:
      case Obj:
      case Tabla:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      r = Sentencias();
raiz.hijos.addLast(r);
    }
    jj_consume_token(0);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Procedure() throws ParseException {Nodo raiz;Token b;
    jj_consume_token(Procedure);
    jj_consume_token(PATH);
    b = jj_consume_token(CADENA);
    jj_consume_token(C_PATH);
    jj_consume_token(C_Proc);
raiz = new Nodo("PROC",b.beginLine,b.beginColumn,b.image);
  {if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Object_U() throws ParseException {Nodo raiz;Token a;
    jj_consume_token(Obj);
    jj_consume_token(PATH);
    a = jj_consume_token(CADENA);
    jj_consume_token(C_PATH);
    jj_consume_token(C_Obj);
raiz = new Nodo("OBJETO",a.beginLine,a.beginColumn,a.image);
  {if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Sentencias() throws ParseException {Nodo raiz;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case Obj:{
      raiz = Object_U();
{if ("" != null) return raiz;}
      break;
      }
    case Tabla:{
      raiz = Tabla();
{if ("" != null) return raiz;}
      break;
      }
    case Procedure:{
      raiz = Procedure();
{if ("" != null) return raiz;}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo Tabla() throws ParseException {Nodo raiz,r,rows;Token a,b;
rows= new Nodo("filas",0,0);
    jj_consume_token(Tabla);
    jj_consume_token(NOMBRE);
    a = jj_consume_token(IDEN);
    jj_consume_token(C_NOMBRE);
    jj_consume_token(PATH);
    b = jj_consume_token(CADENA);
    jj_consume_token(C_PATH);
    jj_consume_token(Rows);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case BOOL:
      case TEXT:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      r = Atributo();
rows.hijos.addLast(r);
    }
    jj_consume_token(C_Rows);
    jj_consume_token(C_Tabla);
raiz = new Nodo("Tabla",a.beginLine,a.beginColumn,a.image,b.image);
  raiz.hijos.addLast(rows);
  {if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Atributo() throws ParseException {Nodo raiz,sent;Token a,b;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      a = jj_consume_token(INT);
      b = jj_consume_token(IDEN);
raiz = new Nodo("ATRIBUTO",a.beginLine,a.beginColumn,a.image,b.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Crs:{
        sent = Caracteristicas();
raiz.hijos.addLast(sent);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(C_INT);
{if ("" != null) return raiz;}
      break;
      }
    case BOOL:{
      a = jj_consume_token(BOOL);
      b = jj_consume_token(IDEN);
raiz = new Nodo("ATRIBUTO",a.beginLine,a.beginColumn,a.image,b.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Crs:{
        sent = Caracteristicas();
raiz.hijos.addLast(sent);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        ;
      }
      jj_consume_token(C_BOOL);
{if ("" != null) return raiz;}
      break;
      }
    case TEXT:{
      a = jj_consume_token(TEXT);
      b = jj_consume_token(IDEN);
raiz = new Nodo("ATRIBUTO",a.beginLine,a.beginColumn,a.image,b.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case Crs:{
        sent = Caracteristicas();
raiz.hijos.addLast(sent);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      jj_consume_token(C_TEXT);
{if ("" != null) return raiz;}
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Nodo Caracteristicas() throws ParseException {Nodo raiz,sent;
raiz = new Nodo("CRS",0,0);
    jj_consume_token(Crs);
    sent = Crs();
raiz.hijos.addLast(sent);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PK:
      case AUTO_INC:
      case FK:
      case NULO:
      case NOT_NULL:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_3;
      }
      sent = Crs();
raiz.hijos.addLast(sent);
    }
    jj_consume_token(C_Crs);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
  }

  final public Nodo Crs() throws ParseException {Token a,b;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PK:{
      jj_consume_token(PK);
{if ("" != null) return new Nodo("PK",token.beginLine,token.beginColumn);}
      break;
      }
    case FK:{
      jj_consume_token(FK);
      a = jj_consume_token(IDEN);
      b = jj_consume_token(IDEN);
{if ("" != null) return new Nodo("FK",a.beginLine,a.beginColumn,a.image,b.image);}
      break;
      }
    case AUTO_INC:{
      jj_consume_token(AUTO_INC);
{if ("" != null) return new Nodo("INC",token.beginLine,token.beginColumn);}
      break;
      }
    case NULO:{
      jj_consume_token(NULO);
{if ("" != null) return new Nodo("NULL",token.beginLine,token.beginColumn);}
      break;
      }
    case NOT_NULL:{
      jj_consume_token(NOT_NULL);
{if ("" != null) return new Nodo("NOT_NULL",token.beginLine,token.beginColumn);}
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public registro_dbTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x540,0x540,0x1c000,0x1000000,0x1000000,0x1000000,0x1c000,0x7c000000,0x7c000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public registro_db(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public registro_db(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new registro_dbTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public registro_db(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new registro_dbTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public registro_db(registro_dbTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(registro_dbTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[36];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 36; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
