/* Generated By:JavaCC: Do not edit this line. registro_procConstants.java */
package gramatica.registro_proc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface registro_procConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Procedure = 6;
  /** RegularExpression Id. */
  int C_Proc = 7;
  /** RegularExpression Id. */
  int FUNC = 8;
  /** RegularExpression Id. */
  int C_FUNC = 9;
  /** RegularExpression Id. */
  int RET = 10;
  /** RegularExpression Id. */
  int C_RET = 11;
  /** RegularExpression Id. */
  int Src = 12;
  /** RegularExpression Id. */
  int C_Scr = 13;
  /** RegularExpression Id. */
  int Param = 14;
  /** RegularExpression Id. */
  int C_Param = 15;
  /** RegularExpression Id. */
  int Obj = 16;
  /** RegularExpression Id. */
  int C_Obj = 17;
  /** RegularExpression Id. */
  int Tabla = 18;
  /** RegularExpression Id. */
  int C_Tabla = 19;
  /** RegularExpression Id. */
  int Rows = 20;
  /** RegularExpression Id. */
  int C_Rows = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int BOOL = 23;
  /** RegularExpression Id. */
  int TEXT = 24;
  /** RegularExpression Id. */
  int C_INT = 25;
  /** RegularExpression Id. */
  int C_BOOL = 26;
  /** RegularExpression Id. */
  int C_TEXT = 27;
  /** RegularExpression Id. */
  int NOMBRE = 28;
  /** RegularExpression Id. */
  int C_NOMBRE = 29;
  /** RegularExpression Id. */
  int PATH = 30;
  /** RegularExpression Id. */
  int C_PATH = 31;
  /** RegularExpression Id. */
  int DATE = 32;
  /** RegularExpression Id. */
  int DATETIME = 33;
  /** RegularExpression Id. */
  int C_DATE = 34;
  /** RegularExpression Id. */
  int C_DATETIME = 35;
  /** RegularExpression Id. */
  int NUM = 36;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 37;
  /** RegularExpression Id. */
  int IDEN = 38;
  /** RegularExpression Id. */
  int CADENA = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<Proc>\"",
    "\"</Proc>\"",
    "\"<Func>\"",
    "\"</Func>\"",
    "\"<return>\"",
    "\"</return>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<params>\"",
    "\"</params>\"",
    "\"<Object>\"",
    "\"</Object>\"",
    "\"<Tabla>\"",
    "\"</Tabla>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<integer>\"",
    "\"<bool>\"",
    "\"<text>\"",
    "\"</integer>\"",
    "\"</bool>\"",
    "\"</text>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "\"<DATE>\"",
    "\"<DATETIME>\"",
    "\"</DATE>\"",
    "\"</DATETIME>\"",
    "<NUM>",
    "<DECIMAL_LITERAL>",
    "<IDEN>",
    "<CADENA>",
    "\"<\"",
    "\">\"",
    "\"/\"",
  };

}
