/* Generated By:JavaCC: Do not edit this line. registro_procConstants.java */
package gramatica.registro_proc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface registro_procConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Procedure = 6;
  /** RegularExpression Id. */
  int C_Proc = 7;
  /** RegularExpression Id. */
  int Src = 8;
  /** RegularExpression Id. */
  int C_Scr = 9;
  /** RegularExpression Id. */
  int Param = 10;
  /** RegularExpression Id. */
  int C_Param = 11;
  /** RegularExpression Id. */
  int Obj = 12;
  /** RegularExpression Id. */
  int C_Obj = 13;
  /** RegularExpression Id. */
  int Tabla = 14;
  /** RegularExpression Id. */
  int C_Tabla = 15;
  /** RegularExpression Id. */
  int Rows = 16;
  /** RegularExpression Id. */
  int C_Rows = 17;
  /** RegularExpression Id. */
  int INT = 18;
  /** RegularExpression Id. */
  int BOOL = 19;
  /** RegularExpression Id. */
  int TEXT = 20;
  /** RegularExpression Id. */
  int C_INT = 21;
  /** RegularExpression Id. */
  int C_BOOL = 22;
  /** RegularExpression Id. */
  int C_TEXT = 23;
  /** RegularExpression Id. */
  int NOMBRE = 24;
  /** RegularExpression Id. */
  int C_NOMBRE = 25;
  /** RegularExpression Id. */
  int PATH = 26;
  /** RegularExpression Id. */
  int C_PATH = 27;
  /** RegularExpression Id. */
  int NUM = 28;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 29;
  /** RegularExpression Id. */
  int IDEN = 30;
  /** RegularExpression Id. */
  int CADENA = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<Proc>\"",
    "\"</Proc>\"",
    "\"<src>\"",
    "\"</src>\"",
    "\"<params>\"",
    "\"</params>\"",
    "\"<Object>\"",
    "\"</Object>\"",
    "\"<Tabla>\"",
    "\"</Tabla>\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "\"<int>\"",
    "\"<bool>\"",
    "\"<text>\"",
    "\"</int>\"",
    "\"</bool>\"",
    "\"</text>\"",
    "\"<nombre>\"",
    "\"</nombre>\"",
    "\"<path>\"",
    "\"</path>\"",
    "<NUM>",
    "<DECIMAL_LITERAL>",
    "<IDEN>",
    "<CADENA>",
  };

}
