/* Generated By:JavaCC: Do not edit this line. registro_tablaConstants.java */
package gramatica.registro_tabla;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface registro_tablaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAYOR = 6;
  /** RegularExpression Id. */
  int MENOR = 7;
  /** RegularExpression Id. */
  int SLASH = 8;
  /** RegularExpression Id. */
  int Rows = 9;
  /** RegularExpression Id. */
  int C_Rows = 10;
  /** RegularExpression Id. */
  int IDEN = 11;
  /** RegularExpression Id. */
  int C_IDE = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\">\"",
    "\"<\"",
    "\"/\"",
    "\"<rows>\"",
    "\"</rows>\"",
    "<IDEN>",
    "<C_IDE>",
  };

}
